### PR TITLE
Updated support page - Ouisync on Windows part

### PR DESCRIPTION
**Pull request by IvanaBlzvc**
Added Ouisync on windows, with its strings and images needed.  No other changes.

### CODE REVIEW

**Review by jnny — CHANGES_REQUESTED** [review]
One question: Why include all these steps instead of just linking to the Ouisync listing on the Microsoft Store directly?

> "faqContent411": "To install Ouisync on your Windows machine, please go to the [Microsoft App Store](https://apps.microsoft.com/), type 'Ouisync' in the search box and click on the Download button.",

**Comment by IvanaBlzvc** [comment]
Why include all these steps?  because I don't know what users will want/not want to see.  So I err on too much, rather than too little.

**Comment by IvanaBlzvc** [comment]
Thanks for doing the copyedits @jnny

**Review by jnny — APPROVED** [review]
I think this looks good, awesome work! Merging but would appreciate if @willow446 could do a check on the live version :)

**Pull request merged**
